# Generated by Django 5.2.5 on 2026-02-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caleory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
